eureka:
  client:
    serviceUrl: 
    #eureka注册中心地址
      defaultZone: http://localhost:8888/eureka/
server:
#项目端口号
  port: 3011
spring:
  application: 
  #服务名称,随便写
    name: service-zuul
  http: 
    multipart: 
      file-size-threshold: 1Mb
      max-file-size: 1000Mb
      max-request-size: 1000Mb
    
# 下面整个树都非必须，如果不配置，
#将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 
#路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
#------------------------------ 默认行为 ----------------------------------------
#使用Eureka注册中心则zuul服务网关会自动生成以下路由规则
zuul: #需要忽略的头部信息，不在传播到其他服务 
  sensitive-headers: Access-Control-Allow-Origin 
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host: 
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 60000

cloudplatform-service-local: 
#设置ribbon的请求超时时间，大文件上传必须调高此时间
  ribbon: 
    ConnectTimeout: 80000 
    ReadTimeout: 30000 
    #同一个Server重试的次数(除去首次) 
    MaxAutoRetries: 3 
    #切换到不同Server的次数 
    MaxAutoRetriesNextServer: 3 
    #对所有方法进行重试 
    okToRetryOnAllOperations: true 
    eureka: 
      enabled: true

security: 
  oauth2: 
    resource: 
      ####从认证授权中心上验证token
      tokenInfoUri: http://localhost:3011/chenyongjia-oauth/oauth/check_token
      preferTokenInfo: true
    client: 
      accessTokenUri: http://localhost:3011/chenyongjia-oauth/oauth/token
      userAuthorizationUri: http://localhost:3011/chenyongjia-oauth/oauth/authorize
      clientId: client_1
      clientSecret: 123456 
#zuul:
#  routes:
#    api-a:
#      path: /service-provider/**
#      service-id: service-provider
#    api-b:
#      path: /service-consumer/**
#      service-id: service-consumer

#访问http://127.0.0.1:8889/service-provider/getFuture?token=666
#会被服务网关zuul转发到http://127.0.0.1:8002/getFuture?token=666
#http://127.0.0.1:8889/service-consumer/getProviderFuture?token=666
#会被服务网关zuul被转发到http://127.0.0.1:8001/getProviderFutur?token=666
#-------------------------------- 自定义配置  --------------------------------------
#亦可以自定义配置zuul服务网关的路由规则
#zuul:
#  routes:
#    api-a:
#      path: /api-provider/**
#      service-id: service-provider
#    api-b:
#      path: /api-consumer/**
#      service-id: service-consumer

#发送请求http://127.0.0.1:8889/api-consumer/getProviderFuture?token=666
#会被服务网关zuul被转发到http://127.0.0.1:8001/getProviderFutur?token=666

