#debug: true
eureka:
  client:
    serviceUrl:
    #eureka注册中心地址固定就这样写
      defaultZone: http://localhost:8888/eureka/
      
server:
#项目端口号
  port: 3030
  servlet: 
    context-path: /WangMengXia

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
  #服务名称
    name: wangmengxia
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
    #数据库意思是:机构权限文件
    url: jdbc:mysql://127.0.0.1:3306/wangpost?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false 
    username: root 
    password: root 
  #redis数据库配置
  #redis:
    #host: 127.0.0.1
    #database: 0
  # SpringDateJpa 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    ##运行时输出jpa执行的sql语句
    show-sql: true
    ## spring-boot-starter-data-jpa自动映射创建表动作 配置: 有表更新,无表创建
    hibernate: 
      ddl-auto: update
  #集中解决各种编码问题
  banner:
    charset: UTF-8
  http: 
    encoding: 
      charset: UTF-8
      enabled: true 
      force: true
  messages:
    encoding: UTF-8
  #     spring mvc 视图解析器   
  mvc: 
    view: 
      prefix: /
      suffix: .html
  # 时间格式化 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
  # 时区设置
    time-zone: GMT+8
#启用Feign中hystrix熔断器、依赖隔离、服务降级
#feign:
   #hystrix:
     #enabled: true   
#断路器的超时时间,下级服务返回超出熔断器时间，即便成功，消费端消息也是TIMEOUT,所以一般断路器的超时时间需要大于ribbon的超时时间。
#服务的返回时间大于ribbon的超时时间，会触发重试
##默认=1000,太小,修改为50秒
#hystrix:
   #command: 
     #default: 
       #execution:
         #timeout:
           #enabled: true
         #isolation:
           #thread: 
             #timeoutInMilliseconds: 50000 
#security:
  #oauth2:
   # resource:
      ####从认证授权中心上验证token
      #tokenInfoUri: http://localhost:3012/oauth/check_token
     # preferTokenInfo: true
   # client:
     # accessTokenUri: http://localhost:3012/oauth/token
     # userAuthorizationUri: http://localhost:3012/oauth/authorize
#      ###appid
     # clientId: client_1
#      ###appSecret
    #  clientSecret: 123456
   
